name: CI
on:
  merge_group:
  pull_request:
  push:
    branches: [ main ]
concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}
permissions:
  contents: read
env:
  CARGO_TERM_COLOR: always
jobs:
  validate-commits:
    name: Validate commit messages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check conventional commits
        uses: webiny/action-conventional-commits@v1.3.0
  checks:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - run: cargo check --workspace --all-targets
      - run: cargo check --workspace --all-targets --no-default-features
  lints:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: rustfmt, clippy
      - name: Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: common
      - run: cargo fmt --all -- --check
      - run: cargo doc --workspace --no-deps
      - run: cargo clippy --workspace --all-targets -- -D warnings
  test:
    runs-on: ubuntu-latest
    needs: [checks, lints]
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo test --workspace --verbose