name: Pull request
on:
  pull_request_target:
    branches: [main]
    types: [opened, edited, synchronize, reopened]
jobs:
  validate-title:
    name: Validate conventional commits in PR title
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: marocchino/sticky-pull-request-comment@v2
        if: always() && (steps.lint_pr_title.outputs.error_message != null)
        with:
          header: pr-title-lint-error
          message: |
            We require pull request titles to follow the 
            [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/), 
            and it looks like your proposed title needs to be adjusted.
            
            Details:
            
            ```
            ${{ steps.lint_pr_title.outputs.error_message }}
            ```
      - if: ${{ steps.lint_pr_title.outputs.error_message == null }}
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: pr-title-lint-error
          delete: true
  label:
    name: Set labels
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v5